example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax
from wishlist.views import add_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/',show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit/', add_wishlist, name='add_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import json
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.urls import reverse

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Alifia Nadiya Putri',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

# Lab 5
@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
        'nama': 'Alifia Nadiya Putri',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def add_wishlist(request: HttpRequest):
     if request.method == "POST":
         nama_barang = request.POST.get("nama_barang")
         harga_barang = request.POST.get("harga_barang")
         deskripsi = request.POST.get("deskripsi")

         new_barang = BarangWishlist(
             nama_barang=nama_barang,
             harga_barang=harga_barang,
             deskripsi=deskripsi,
         )
         new_barang.save()
         return HttpResponse(
             serializers.serialize("json", [new_barang]),
             content_type="application/json",
         )

     return HttpResponse("Invalid method", status_code=405)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<nav class="navbar" style="background-color:#f8ffa8;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0" style="font-weight:bold;font-size: 30px;">Login User</span>
    </div>
</nav>

<div class = "login" style="text-align: center;">

    <h1 style="margin-top: 20px;">Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table class="table solid border w-auto" style="margin-left: auto; margin-right: auto;">
            <tr>
                <td style="vertical-align:middle;">Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td style="vertical-align:middle;">Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
        </table>
        <td><input class="btn btn-primary" type="submit" value="Login" style="margin-bottom: 15px;"></td>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li style="list-style: none;">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  
<nav class="navbar" style="background-color:#f8ffa8;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0" style="font-weight:bold;font-size: 30px;">Registrasi Akun</span>
    </div>
</nav>

<div class = "login" style="text-align: center;">
    
    <h1 style="margin-top: 20px;">Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table class="table table-bordered w-auto" style="text-align: left;margin-left: auto; margin-right: auto;">  
                {{ form.as_table }}  
            </table>  
            <td><input class="btn btn-primary" type="submit" value="Daftar"/></td> 
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li style="list-style: none;">{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar" style="background-color:#f8ffa8;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0" style="font-weight:bold;font-size: 30px;">Alifia Nadiya Putri</span>
      <a class="btn btn-primary" style="background-color: rgb(0, 0, 0);" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
    </div>
</nav>

<table class="table table-bordered w-auto" style="margin-left: auto; margin-right: auto;margin-top: 50px;font-family: Calibri;font-size: 20px;">
    <tr style="background-color:#fcffd7;">
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
</table>
<h5 style="text-align: center;padding-top: 20px;font-size: medium;">Sesi terakhir login: {{ last_login }}</h5>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<body>
    <nav class="navbar" style="background-color:#f8ffa8;">
        <div class="container-fluid">
        <span class="navbar-brand mb-0" style="font-weight:bold;font-size: 30px;">Alifia Nadiya Putri</span>
        <a class="btn btn-primary" style="background-color: rgb(0, 0, 0);" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
        </div>
    </nav>

    <table class="table table-bordered w-auto" style="margin-left: auto; margin-right: auto;margin-top: 50px;font-family: Calibri;font-size: 20px;">
        <thead style="background-color:#fcffd7;">
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </thead>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
                <tbody id="table-data"></tbody>
    </table>

    <h3>Create Wishlist</h3>
    <form method="POST" action="" class="d-flex flex-column">
      {% csrf_token %}
      <div class="d-flex flex-column mb-2">
        <label for="nama_barang">Nama Barang</label>
        <input type="text" name="nama_barang" id="nama_barang" placeholder="Nama Barang" class="form-control"/>
      </div>
      <div class="d-flex flex-column mb-2">
        <label for="harga_barang">Harga Barang</label>
        <input name="harga_barang" id="harga_barang" placeholder="Harga Barang" class="form-control"/>
      </div>
      <div class="d-flex flex-column mb-2">
        <label for="deskripsi">Deskripsi</label>
        <input name="deskripsi" id="deskripsi" placeholder="Deskripsi" class="form-control"/>
      </div>
        <input class="btn btn-primary" type="submit" value="Submit" id="newBtn">
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
      function postNew(e) {
        e.preventDefault()
        const namaBarang = $("#nama_barang").val()
        const hargaBarang = $("#harga_barang").val()
        const deskripsi = $("#deskripsi").val()
    
        const data = {
          nama_barang: namaBarang,
          harga_barang: hargaBarang,
          deskripsi,
          csrfmiddlewaretoken: "{{ csrf_token }}"
        }
    
        $.ajax({
          type: 'POST',
          url: '{% url "wishlist:add_wishlist" %}',
          data: data, 
          success: () => {
            alert("Done!")
            fetchData()
          },
          // contentType: "application/json",
          dataType: 'json'
        });
      }
    
      function writeTable(data) {
        const table = $("#table-data")
        table.empty()
        for (let i = 0; i < data.length; i++) {
          table.append(`
            <tr>
              <td>${data[i].fields.nama_barang}</td>
              <td>${data[i].fields.harga_barang}</td>
              <td>${data[i].fields.deskripsi}</td>
            </tr>
            `)
        }
      }
    
      function fetchData() {
        $.get("/wishlist/json", writeTable)
      }
    
      $(document).ready(() => {
        $("#newBtn").click(postNew)
        fetchData()
      })
    </script>
</body>
<h5 style="text-align: center;padding-top: 20px;font-size: medium;">Sesi terakhir login: {{ last_login }}</h5>

{% endblock content %}